language: php
php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer require --dev "laravel/laravel=6.x"
  - composer install --dev --prefer-source --no-interaction

script: vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
